; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DCUGen"
#define MyAppVersion "4.3"
#define MyAppPublisher "Beherrit"
#define MyAppExeName "DCUQA.exe"

[Setup]
AppId={{806D8387-C156-4D87-B4ED-E781A9F3C50B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=mysetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\json\*"; DestDir: "{app}\json"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\json\charactername.xlsx"; DestDir: "{app}\json"; Flags: ignoreversion

; Images by category
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\actions\action_*"; DestDir: "{app}\images\actions"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\combat_misc\cm_*"; DestDir: "{app}\images\combat_misc"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\environmental\env_*"; DestDir: "{app}\images\environmental"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\extras\ex_*"; DestDir: "{app}\images\extras"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\flaws\flaw_*"; DestDir: "{app}\images\flaws"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\maneuvers\man_*"; DestDir: "{app}\images\maneuvers"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\skills\skills_*"; DestDir: "{app}\images\skills"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\Users\Lawre\Documents\GitHub\DCUGenChar\dist\images\bmt_skills\bmt_*"; DestDir: "{app}\images\bmt_skills"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
