// The Bio page: a random life history for a character (family, timeline, people, personality,
// secrets, GM hooks), generated by engine/lifepath.js and editable.

import { h, toast, copyText, inkFor } from './dom.js';
import { generateBio, rerollSection, bioText } from '../engine/lifepath.js';
import { randomSeed } from '../engine/rng.js';

const SIDE_LABEL = { light: 'Lightside', dark: 'Darkside', neutral: 'Neutral', exotic: 'Exotic' };

/**
 * change(fn): clone the character, apply fn, save (same helper the sheet uses). May be null (read-only).
 */
export function renderBio(ch, R, { change, toolbar, onOpenPerson } = {}) {
  const open = onOpenPerson || null;
  const hero = ch.theme?.color || '#c8202f';
  const id = ch.identity || {};
  const bio = ch.bio;
  const head = h('div', { class: 'file-head' },
    h('div', { class: 'eyebrow' }, 'Biography'),
    h('h1', { class: 'codename' }, id.codename || 'Unnamed'),
    h('div', { class: 'realname' }, [id.realName, id.age ? `age ${id.age}` : null, id.occupation, id.homeland?.country].filter(Boolean).join(' · ')));
  head.style.setProperty('--hero', hero);
  head.style.setProperty('--hero-ink', inkFor(hero));

  const regen = () => change?.((c) => { c.bio = generateBio(R, c, { seed: randomSeed() }); });

  if (!bio) {
    const file = h('article', { class: 'file bio' }, head, toolbar || null,
      h('div', { class: 'bio-empty' },
        h('p', null, 'No life story yet. Roll one: family, childhood, the events that made them, the people in their life, personality, secrets and story hooks for the GM.'),
        change ? h('button', { class: 'btn primary big', type: 'button', id: 'bio-generate', onClick: regen }, 'Roll a life story') : null));
    file.style.setProperty('--hero', hero);
    return file;
  }

  const reroll = (sectionId) => change?.((c) => {
    try { c.bio = rerollSection(R, c, c.bio, sectionId, { seed: randomSeed() }); } catch (e) { toast(e.message); }
  });

  const summary = h('section', { class: 'sec bio-summary' },
    h('h3', null, 'Their story', change ? h('span', { class: 'pts no-print' }, h('button', { class: 'linkish', type: 'button', onClick: regen }, 'Roll a new life')) : null),
    change
      ? h('textarea', { class: 'bio-summary-edit', id: 'bio-summary', 'aria-label': 'Biography summary', onChange: (e) => change((c) => { c.bio = { ...c.bio, summary: e.target.value, edited: true }; }) }, bio.summary || '')
      : h('p', null, bio.summary));

  const sections = (bio.sections || []).map((s) => h('section', { class: 'sec bio-sec' },
    h('h3', null, s.title, change ? h('span', { class: 'pts no-print' }, h('button', { class: 'linkish', type: 'button', title: `Re-roll ${s.title}`, onClick: () => reroll(s.id) }, '🎲 re-roll')) : null),
    h('dl', { class: 'bio-dl' }, (s.items || []).map((it) => [h('dt', null, it.label), h('dd', null, it.text)]))));

  const timeline = (bio.timeline || []).length ? h('section', { class: 'sec' },
    h('h3', null, 'Life timeline'),
    h('ol', { class: 'bio-timeline' }, bio.timeline.map((t) => h('li', null,
      h('span', { class: 'bio-age num' }, t.age != null ? t.age : '—'),
      h('div', null, t.stage ? h('span', { class: 'bio-stage' }, t.stage) : null, h('span', null, t.text)))))) : null;

  const fam = bio.family || {};
  const family = (fam.parents?.length || fam.siblings?.length || fam.structure) ? h('section', { class: 'sec' },
    h('h3', null, 'Family'),
    fam.structure ? h('p', { class: 'bio-note' }, fam.structure) : null,
    h('ul', { class: 'bio-people' },
      (fam.parents || []).map((p) => person(p.name, p.role, [p.occupation, p.trait].filter(Boolean).join('; '), p.status, open && (() => open(p, 'parent')))),
      (fam.siblings || []).map((p) => person(p.name, p.relation, [p.age != null ? `age ${p.age}` : null, p.note].filter(Boolean).join('; '), p.status, open && (() => open(p, 'sibling')))))) : null;

  const people = (bio.people || []).length ? h('section', { class: 'sec' },
    h('h3', null, 'People in their life', open ? h('span', { class: 'pts no-print' }, 'tap a name to meet them') : null),
    h('ul', { class: 'bio-people' }, bio.people.map((p) => person(p.name, p.relation, p.who, p.status, open && (() => open(p, 'person')))))) : null;

  const pers = bio.personality || {};
  const personality = h('section', { class: 'sec' },
    h('h3', null, 'Personality'),
    (pers.traits || []).length ? h('div', { class: 'bio-traits' }, pers.traits.map((t) => h('span', { class: `bio-trait ${t.side || ''}`, title: SIDE_LABEL[t.side] || '' }, t.name, t.strength && t.strength !== 'mild' ? h('small', null, ` · ${t.strength}`) : null))) : null,
    h('dl', { class: 'bio-dl' },
      list('Values', pers.values), list('Fears', pers.fears), list('Habits', pers.habits), list('Likes', pers.likes), list('Dislikes', pers.dislikes),
      pers.voice ? [h('dt', null, 'Roleplay it'), h('dd', null, pers.voice)] : null));

  const inner = h('section', { class: 'sec' },
    h('h3', null, 'Inner life'),
    h('dl', { class: 'bio-dl' }, list('Motivations', bio.motivations), list('Secrets', bio.secrets), list('Regrets', bio.regrets), list('Hopes', bio.hopes)));

  const haveComp = new Set((ch.complications || []).map((c) => `${c.type}|${c.text}`));
  const gm = h('section', { class: 'sec bio-gm' },
    h('h3', null, 'For the GM'),
    (bio.hooks || []).length ? h('ul', { class: 'bio-hooks' }, bio.hooks.map((x) => h('li', null, x))) : null,
    (bio.complications || []).length ? [h('div', { class: 'label', style: { margin: '10px 0 6px' } }, 'Complications from their past (DCA 27)'),
      h('ul', { class: 'bio-comps' }, bio.complications.map((c) => h('li', null, h('b', null, `${c.type}: `), c.text,
        change && !haveComp.has(`${c.type}|${c.text}`) ? h('button', { class: 'btn sm no-print', type: 'button', onClick: () => change((x) => { x.complications = [...(x.complications || []), { type: c.type, text: c.text }]; }) }, 'Add to sheet') : h('span', { class: 'bio-added' }, ' ✓ on sheet'))))] : null,
    (bio.benefits?.skills?.length || bio.benefits?.advantages?.length) ? [h('div', { class: 'label', style: { margin: '10px 0 6px' } }, 'What their past suggests (buy with points if you like)'),
      h('ul', { class: 'bio-comps' },
        (bio.benefits.skills || []).map((s) => h('li', null, h('b', null, `${s.name}${s.spec ? ` (${s.spec})` : ''}`), s.why ? `: ${s.why}` : '')),
        (bio.benefits.advantages || []).map((a) => h('li', null, h('b', null, a.name), a.why ? `: ${a.why}` : '')))] : null);

  const actions = h('div', { class: 'btn-row no-print', style: { marginTop: '4px' } },
    h('button', { class: 'btn', type: 'button', onClick: async () => toast((await copyText(bioText(bio))) ? 'Bio copied' : 'Copy failed') }, 'Copy bio text'));

  const file = h('article', { class: 'file bio' }, head, toolbar || null,
    h('div', { class: 'file-body' },
      h('div', { class: 'col' }, summary, timeline, family, people),
      h('div', { class: 'col' }, personality, inner, sections, gm, actions)));
  file.style.setProperty('--hero', hero);
  file.style.setProperty('--hero-ink', inkFor(hero));
  return file;
}

function person(name, relation, who, status, onOpen) {
  return h('li', null,
    h('div', null, onOpen
      ? h('button', { type: 'button', class: 'bio-name-link', title: `Open ${name} as a full character in a new tab`, onClick: onOpen }, name || 'Unnamed', h('span', { class: 'bio-open', 'aria-hidden': 'true' }, ' ↗'))
      : h('b', null, name || 'Unnamed'), relation ? h('span', { class: 'bio-rel' }, relation) : null),
    who ? h('div', { class: 'bio-who' }, who) : null,
    status ? h('div', { class: 'bio-status' }, status) : null);
}

function list(label, arr) {
  if (!arr?.length) return null;
  return [h('dt', null, label), h('dd', null, arr.length === 1 ? arr[0] : h('ul', null, arr.map((x) => h('li', null, x))))];
}
