// The portrait block on the case file, the Bio page and the World.

import { h, toast, copyText, openDialog } from './dom.js';
import { portraitOf, setPortrait, newPortraitSeed, portraitPrompt, PORTRAIT_SERVICE } from '../engine/portrait.js';

const CREDIT = `Generated by ${PORTRAIT_SERVICE.name}: free and open source, no account. Only the prompt is sent to it; the image is not stored anywhere but your browser's cache.`;

/**
 * change(fn): clone, apply, save. Omit it for a read-only portrait.
 * size: 'file' (case file header) | 'small' (cards)
 */
export function portraitBlock(ch, { change, size = 'file' } = {}) {
  const p = portraitOf(ch);
  if (p.hidden && !change) return null;
  const img = h('img', { class: 'portrait-img', src: p.url, alt: `Portrait of ${ch.identity?.codename || 'the character'}`, loading: 'lazy', width: 512, height: 640, referrerpolicy: 'no-referrer' });
  const status = h('div', { class: 'portrait-status' }, 'Painting…');
  img.addEventListener('load', () => { status.hidden = true; });
  img.addEventListener('error', () => { status.textContent = 'Couldn\'t load the portrait (needs internet). Try again later or re-roll.'; status.classList.add('bad'); });
  const editPrompt = async () => {
    const ta = h('textarea', { style: { minHeight: '140px' } }, p.prompt);
    const ok = await openDialog({
      title: 'Portrait prompt',
      body: [h('p', { style: { margin: 0 } }, 'Built from the sheet, the looks and the bio. Change anything; "Reset" goes back to the generated prompt.'), ta, h('p', { class: 'hint', style: { margin: 0 } }, CREDIT)],
      buttons: [{ label: 'Cancel', value: null }, { label: 'Reset to generated', value: 'reset' }, { label: 'Use this prompt', value: 'save', primary: true }],
    });
    if (ok === 'save') change((c) => setPortrait(c, { prompt: ta.value.trim(), seed: newPortraitSeed() }));
    if (ok === 'reset') change((c) => setPortrait(c, { prompt: '', seed: newPortraitSeed() }));
  };
  const controls = change ? h('div', { class: 'portrait-tools no-print' },
    p.hidden
      ? h('button', { class: 'btn sm', type: 'button', title: CREDIT, onClick: () => change((c) => setPortrait(c, { hidden: false, seed: c.portrait?.seed ?? newPortraitSeed() })) }, '🖼 Generate a portrait')
      : [
        h('button', { class: 'btn sm', type: 'button', title: 'Same prompt, new dice', onClick: () => change((c) => setPortrait(c, { seed: newPortraitSeed() })) }, '🎲 New portrait'),
        h('button', { class: 'btn sm', type: 'button', onClick: editPrompt }, p.custom ? 'Prompt (edited)' : 'Prompt'),
        h('button', { class: 'btn sm ghost', type: 'button', title: 'Copy the prompt to use in any other image tool', onClick: async () => toast((await copyText(p.prompt)) ? 'Prompt copied' : 'Copy failed') }, 'Copy'),
        h('button', { class: 'x', type: 'button', 'aria-label': 'Hide the portrait', title: 'Hide the portrait', onClick: () => change((c) => setPortrait(c, { hidden: true })) }, '✕'),
      ]) : null;
  if (p.hidden) return h('div', { class: `portrait ${size} hidden` }, controls);
  return h('div', { class: `portrait ${size}`, title: p.prompt }, h('div', { class: 'portrait-frame' }, img, status), controls);
}

export { portraitPrompt };
