// Build steps, no dependencies:
//   node tools/build.mjs data  -> src/generated/rulesdata.js (all JSON data as one module)
//   node tools/build.mjs all   -> data + DCUGen.html (one self-contained file, double-click to open)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'data');
const SRC = path.join(ROOT, 'src');
const read = (p) => fs.readFileSync(p, 'utf8');
const readJson = (p) => JSON.parse(read(p));

function jsonFolder(dir) {
  const full = path.join(DATA, dir);
  if (!fs.existsSync(full)) return {};
  return Object.fromEntries(
    fs.readdirSync(full).filter((f) => f.endsWith('.json')).sort()
      .map((f) => [path.basename(f, '.json'), readJson(path.join(full, f))]),
  );
}

function buildData() {
  const opt = (name, fallback) => (fs.existsSync(path.join(DATA, name)) ? readJson(path.join(DATA, name)) : fallback);
  const raw = {
    effects: readJson(path.join(DATA, 'effects.json')),
    modifiers: readJson(path.join(DATA, 'modifiers.json')),
    specificModifiers: Object.fromEntries(
      Object.entries(readJson(path.join(DATA, 'specific_modifiers.json'))).filter(([k]) => !k.startsWith('_')),
    ),
    advantages: opt('advantages.json', []),
    skills: readJson(path.join(DATA, 'skills.json')),
    skillGuide: opt('skill_guide.json', []),
    equipment: opt('equipment.json', { weapons: [], armor: [], gear: [], devices: [] }),
    styles: opt('styles.json', []),
    archetypes: opt('archetypes.json', []),
    themes: opt('themes.json', []),
    flavor: jsonFolder('flavor'),
    catalog: jsonFolder('catalog'),
    reference: opt('reference.json', null),
    vehicles: opt('vehicles.json', null), headquarters: opt('headquarters.json', null),
    gm: jsonFolder('gm'),
    lifepath: jsonFolder('lifepath'),
    gear: jsonFolder('gear'),
    spaceRules: opt('space_rules.json', null),
  };
  const out = path.join(SRC, 'generated');
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(
    path.join(out, 'rulesdata.js'),
    `// Generated by tools/build.mjs from data/*.json. Do not edit by hand.\nexport const RAW = ${JSON.stringify(raw)};\n`,
  );
  const catalogCount = Object.values(raw.catalog).reduce((s, l) => s + l.length, 0);
  console.log(`data: ${raw.effects.length} effects, ${raw.advantages.length} advantages, ${raw.archetypes.length} archetypes, ${raw.themes.length} themes, ${catalogCount} catalog entries`);
}

// ---- tiny bundler: ES modules -> one script --------------------------------------------
// Each module becomes a function scope in a registry; imports become destructuring from it.

const IMPORT_RE = /^import\s+\{([\s\S]*?)\}\s+from\s+['"](.+?)['"];?\s*$/gm;

function collect(entry, seen = new Set(), order = []) {
  const file = path.resolve(entry);
  if (seen.has(file)) return order;
  seen.add(file);
  const code = read(file);
  for (const m of code.matchAll(IMPORT_RE)) collect(path.resolve(path.dirname(file), m[2]), seen, order);
  order.push(file);
  return order;
}

function wrapModule(file) {
  const id = path.relative(ROOT, file).split(path.sep).join('/');
  let code = read(file);
  const exported = new Set();
  code = code.replace(IMPORT_RE, (_, names, from) => {
    const dep = path.relative(ROOT, path.resolve(path.dirname(file), from)).split(path.sep).join('/');
    const list = names.split(',').map((n) => n.trim()).filter(Boolean).map((n) => n.replace(/\s+as\s+/, ': '));
    return `const { ${list.join(', ')} } = __mods[${JSON.stringify(dep)}];`;
  });
  code = code.replace(/^export\s+\{([^}]*)\};?\s*$/gm, (_, names) => {
    for (const n of names.split(',').map((x) => x.trim()).filter(Boolean)) exported.add(n.replace(/\s+as\s+/, ': '));
    return '';
  });
  code = code.replace(/^export\s+(?:default\s+)?((?:async\s+)?function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)/gm, (_, kw, name) => {
    exported.add(name);
    return `${kw} ${name}`;
  });
  return `__mods[${JSON.stringify(id)}] = (() => {\n${code}\nreturn { ${[...exported].join(', ')} };\n})();`;
}

function bundle() {
  const entry = path.join(SRC, 'app', 'app.js');
  const files = collect(entry);
  const js = `const __mods = {};\n${files.map(wrapModule).join('\n\n')}`;
  const css = read(path.join(SRC, 'app', 'app.css'));
  const template = fs.readFileSync(path.join(DATA, 'sheet_template.xlsx')).toString('base64');
  let html = read(path.join(SRC, 'app', 'index.html'));
  html = html
    .replace(/<link rel="stylesheet" href="app.css">/, () => `<style>\n${css}\n</style>`)
    .replace(/<script type="module" src="app.js"><\/script>/, () =>
      `<script>window.DCUGEN_SHEET_TEMPLATE = "${template}";</script>\n<script>\n(() => {\n"use strict";\n${js}\n})();\n</script>`);
  // The whole app in one file at the repository root: open it, or send it to anyone.
  fs.writeFileSync(path.join(ROOT, 'DCUGen.html'), html);
  console.log(`bundle: ${files.length} modules -> DCUGen.html (${Math.round(html.length / 1024)} KB)`);
}

const step = process.argv[2] || 'all';
if (step === 'data' || step === 'all') buildData();
if (step === 'all' || step === 'bundle') bundle();
